import UIKit

//You are given two strings s and t.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Return the letter that was added to t

func findTheDifference(_ s: String, _ t: String) -> Character {
        //create dictionary
        var dict = [Character: Int]()
        //loop through strings and update val on dict
        for char in s {
         dict[char] = (dict[char] ?? 0) + 1
        }
        for char in t {
            dict[char] = (dict[char] ?? 0) + 1
        }
        //return character that was only added once

        for key in dict.keys {
            if let value = dict[key], value % 2 != 0 {
                return key
            }
        }
        
        return Character("")

    }

findTheDifference("abcd", "abcde")
findTheDifference("a", "aa")
findTheDifference("", "y")
